groupmanagement:
    - 
        url: http://www.facebook.com/groups/sanxuatgiaydephcm
        type: dep
        number_of_posts: 5
        member_approve: yes
        decline_if:
            livestream: yes
            reshare: yes
            have_keywords: 
                - vay tiền
                - ngân hàng
                - tài khoản
                - bán gấp
                - Lãi suất
                - v.a.y
                - T.R.Ả G.Ó.P
                - Hỗ trợ vốn
        approve_if:
            have_keywords:
                - giày dép
                - chỉ
                - gia công
                - sản xuất
                - balo
                - túi xách
                - da bò
                - thợ
                - dép da
                - đế giày
                - dép
                - quai
                - xưởng
                - giày
    - 
        url: https://www.facebook.com/groups/xuongmaygiaconghcm
        type: may
        number_of_posts: 5
        member_approve: yes
        decline_if:
            livestream: yes
            reshare: yes
            have_keywords: 
                - vay tiền
                - Lãi suất
                - ngân hàng
                - tài khoản
                - v.a.y
                - T.R.Ả G.Ó.P
                - Hỗ trợ vốn
                - NỢ XẤU
        approve_if:
            have_keywords:
                - tồn kho
                - thanh lí
                - đầm
                - xưởng
                - ráp sườn
                - áo khoác
                - nỉ
                - hoodie
                - dây kéo
                - cắt
                - gia công
                - quần áo
                - may gia công
                - xưởng sản xuất
                - thợ
                - đồng phục
                - thun
                - áo sơ mi
                - hàng kỹ
                - cắt
                - quai
                - vải
                - may
    