groupmanagement:
    - 
        url: http://www.facebook.com/groups/sanxuatgiaydephcm
        number_of_posts: 20
        member_approve: yes
        decline_if:
            livestream: yes
            reshare: yes
            have_keywords: 
                - vay tiền
                - ngân hàng
                - tài khoản
                - bán gấp
                - v.a.y
        approve_if:
            have_keywords:
                - giày dép
                - chỉ
                - gia công
                - xưởng sản xuất
                - balo
                - túi xách
                - da bò
                - thợ
                - dép da
                - đế giày
                - dép
                - quai
                - xưởng
                - giày
    - 
        url: https://www.facebook.com/groups/xuongmaygiaconghcm
        number_of_posts: 20
        member_approve: yes
        decline_if:
            livestream: yes
            reshare: yes
            have_keywords: 
                - vay tiền
                - ngân hàng
                - tài khoản
                - v.a.y
        approve_if:
            have_keywords:
                - gia công
                - quần áo
                - may gia công
                - xưởng sản xuất
                - thợ
                - đồng phục
                - áo thun
                - áo sơ mi
                - hàng kỹ
                - cắt
                - quai
                - vải
                - may
    